using SAMAToXML.CodeGeneration.Engines;
using SumStruct;
using System;
// CodeGeneration/CodeGenerator.cs
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Teigha.DatabaseServices;
using Teigha.Geometry;

namespace SAMAToXML.CodeGeneration
{

    //public class CodeGenerator
    //{
    //    // 添加配置缓存
    //    private static CodeGenConfig _cachedConfig;

    //    public CodeGenerator(CodeGenConfig config = null)
    //    {
    //        _config = config ?? GetConfig();
    //        // 其他初始化...
    //    }

    //    private CodeGenConfig GetConfig()
    //    {
    //        if (_cachedConfig == null)
    //        {
    //            _cachedConfig = CodeGenConfig.FromApplicationSettings();
    //        }
    //        return _cachedConfig;
    //    }

    //    // 添加模板路径配置
    //    public void SetTemplatePath(string templatePath)
    //    {
    //        _templateEngine.LoadTemplateFromFile(templatePath);
    //    }
    //}

    /// <summary>
    /// 主代码生成器
    /// </summary>
    public class CodeGenerator
    {
        private readonly TemplateEngine _templateEngine;
        private readonly CodeGenConfig _config;
        private readonly CodeFormatter _formatter;

        public CodeGenerator(CodeGenConfig config = null)
        {
            _config = config ?? CodeGenConfig.FromForm2();
            _templateEngine = new TemplateEngine(_config);
            _formatter = new CodeFormatter(_config);
        }

        // 修正包含检查，使用传统方法
        private bool ContainsIgnoringCase(string source, string value)
        {
            if (string.IsNullOrEmpty(source) || string.IsNullOrEmpty(value))
                return false;
            return source.IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0;
        }

        /// <summary>
        /// 从工程数据生成代码
        /// </summary>
        // 修改 CodeGenerator.cs
        public GenerationResult GenerateFromEngineeringData(
    List<SourceBlock> sourceBlocks,
    List<STFunBlockInfo> stBlocks,
    Dictionary<ObjectId, LineStruct> connectionsP,
    Dictionary<ObjectId, BlockStruct> connectionsB)
        {
            var result = new GenerationResult();
            StringBuilder sb = new StringBuilder();

            try
            {
                // --- 1. 程序头声明 ---
                sb.AppendLine("PROGRAM AutoGeneratedLogic");
                sb.AppendLine("VAR");

                // 1.1 声明所有连接线变量 (去重)
                HashSet<string> allLines = new HashSet<string>();
                foreach (var b in sourceBlocks)
                {
                    if (b.InputVarList != null) foreach (var s in b.InputVarList) allLines.Add(s);
                    if (b.OutputVarList != null) foreach (var s in b.OutputVarList) allLines.Add(s);
                }
                foreach (var lineVar in allLines)
                {
                    sb.AppendLine($"    {lineVar} : REAL;");
                }

                // 1.2 声明功能块实例
                foreach (var block in sourceBlocks)
                {
                    // 尝试查找模板定义
                    var stDef = FindTemplate(stBlocks, block.BlockType);

                    // 如果找到了模板，用模板里的 FunctionName 作为类型；否则用块名
                    string fbType = (stDef != null) ? stDef.FunctionName : block.BlockType;
                    sb.AppendLine($"    {block.BlockCode} : {fbType};");
                }
                sb.AppendLine("END_VAR");

                sb.AppendLine("");
                sb.AppendLine("(* === 逻辑代码 === *)");

                // --- 2. 逻辑体生成 ---
                foreach (var block in sourceBlocks)
                {
                    sb.AppendLine($"(* 块: {block.BlockCode} (类型: {block.BlockType}) *)");
                    sb.Append($"{block.BlockCode}(");

                    // A. 查找对应的 ST 模板定义
                    var stDef = FindTemplate(stBlocks, block.BlockType);

                    if (stDef != null)
                    {
                        // === 关键逻辑：按照模板引脚填充变量 ===
                        List<string> paramsList = new List<string>();

                        // 1. 处理输入引脚 (Inputs)
                        for (int i = 0; i < stDef.Inputs.Count; i++)
                        {
                            string pinName = stDef.Inputs[i].Split(':')[0].Trim(); // 获取引脚名 (去掉类型声明)
                            string value = "0.0"; // 默认值

                            // 检查是否有对应的连接线传入
                            if (block.InputVarList != null && i < block.InputVarList.Count)
                            {
                                value = block.InputVarList[i]; // 填入 "Line_xxxxx"
                            }

                            paramsList.Add($"{pinName} := {value}");
                        }

                        // 2. 处理输出引脚 (Outputs)
                        for (int i = 0; i < stDef.Outputs.Count; i++)
                        {
                            string pinName = stDef.Outputs[i].Split(':')[0].Trim();

                            // 检查是否有对应的连接线传出
                            if (block.OutputVarList != null && i < block.OutputVarList.Count)
                            {
                                string targetVar = block.OutputVarList[i];
                                paramsList.Add($"{pinName} => {targetVar}");
                            }
                            // 如果输出引脚悬空，通常ST里可以不写，或者写 => NULL
                        }

                        // 将所有参数用逗号连接
                        sb.Append(string.Join(", ", paramsList));
                    }
                    else
                    {
                        // 如果没有 ST 定义，生成一个伪代码，防止空白
                        // 【重点】如果没有ST定义，强行生成一个通用调用格式
                        sb.AppendLine($"{block.BlockCode}(");
                        sb.AppendLine("    IN1 := 0.0,"); // 假参数
                        sb.AppendLine("    IN2 := 0.0");  // 假参数
                    }

                    sb.AppendLine(");");
                    sb.AppendLine("");
                }

                sb.AppendLine("END_PROGRAM");
                result.GeneratedCode = sb.ToString();
                result.Statistics["TotalBlocks"] = sourceBlocks.Count.ToString();
            }
            catch (Exception ex)
            {
                result.Errors.Add(new ValidationError { Message = "代码生成异常: " + ex.Message });
            }

            return result;
        }

        // 辅助方法：处理中文名/英文名匹配问题
        private STFunBlockInfo FindTemplate(List<STFunBlockInfo> stBlocks, string blockType)
        {
            if (stBlocks == null) return null;

            // 1. 尝试完全匹配
            var exact = stBlocks.FirstOrDefault(s => s.BlockName == blockType);
            if (exact != null) return exact;

            string cleanName = blockType;
            int lastIdx = blockType.LastIndexOf('_');
            if (lastIdx > 0)
            {
                cleanName = blockType.Substring(0, lastIdx); // 变成 "安全阀"
                var cleanMatch = stBlocks.FirstOrDefault(s => s.BlockName == cleanName);
                if (cleanMatch != null) return cleanMatch;
            }

            // 3. 尝试包含匹配 (解决 "乘法器" vs "乘法器_1" 或 "Multiplier" vs "乘法器" 的问题)
            // 这里假设 Form3 里加载的模板 BlockName 可能是 "乘法器"
            var fuzzy = stBlocks.FirstOrDefault(s => blockType.StartsWith(s.BlockName) || s.BlockName.StartsWith(blockType));

            return fuzzy;
        }

        private UnifiedSystemModel BuildSystemModel(
            List<SourceBlock> sourceBlocks,
            List<STFunBlockInfo> stBlocks,
            Dictionary<ObjectId, LineStruct> connectionsP,
            Dictionary<ObjectId, BlockStruct> connectionsB)
        {
            var model = new UnifiedSystemModel();
            var blockCounter = 1;

            // 将SourceBlock转换为IntegratedBlock
            foreach (var sourceBlock in sourceBlocks)
            {
                var integratedBlock = new IntegratedBlock
                {
                    Id = $"BLK_{blockCounter:D3}",
                    DwgInfo = new BlockReferenceInfo(
                        sourceBlock.BlockType, // type
                        sourceBlock.BlockType + "_" + blockCounter, // name
                        ObjectId.Null, // objectId - 使用默认值
                        new Point3d(0, 0, 0), // position - 使用默认值
                        0, 0, 0, 0, 0, 0 // 其他参数使用默认值
                    )
                    
                };

                // 查找匹配的ST定义
                foreach (var stBlock in stBlocks)
                {
                    if (ContainsIgnoringCase(stBlock.FunctionName, sourceBlock.BlockType) ||
                        ContainsIgnoringCase(stBlock.BlockName, sourceBlock.BlockType))
                    {
                        integratedBlock.StDefinition = stBlock;
                        break;
                    }
                }



                integratedBlock.GenerateInstanceName(blockCounter);

                // 设置输入输出端口
                if (sourceBlock.InputVarList != null)
                {
                    foreach (var input in sourceBlock.InputVarList)
                    {
                        integratedBlock.InputPorts.Add(new PortInfo
                        {
                            Name = input,
                            DataType = "REAL", // 默认为REAL，实际应根据ST定义确定
                            Direction = PortDirection.Input
                        });
                    }
                }

                if (sourceBlock.OutputVarList != null)
                {
                    foreach (var output in sourceBlock.OutputVarList)
                    {
                        integratedBlock.OutputPorts.Add(new PortInfo
                        {
                            Name = output,
                            DataType = "REAL",
                            Direction = PortDirection.Output
                        });
                    }
                }

                model.Blocks.Add(integratedBlock);
                blockCounter++;
            }

            // 构建连接关系
            BuildConnections(model, connectionsP, connectionsB);

            return model;
        }

        private void BuildConnections(UnifiedSystemModel model,
            Dictionary<ObjectId, LineStruct> connectionsP,
            Dictionary<ObjectId, BlockStruct> connectionsB)
        {
            // 简化实现：基于几何位置和连接线建立连接
            // 实际应根据DWG中的实际连接关系来建立

            // 这里只是一个示例，假设每个块按照列表顺序连接
            for (int i = 0; i < model.Blocks.Count - 1; i++)
            {
                var source = model.Blocks[i];
                var target = model.Blocks[i + 1];

                model.Connections.Add(new Connection
                {
                    SourceBlockId = source.Id,
                    TargetBlockId = target.Id,
                    SourcePort = source.OutputPorts.FirstOrDefault()?.Name ?? "OUT",
                    TargetPort = target.InputPorts.FirstOrDefault()?.Name ?? "IN"
                });
            }
        }

        private string GenerateVariableDeclarations(List<IntegratedBlock> blocks)
        {
            var declarations = new StringBuilder();

            // 生成每个块的实例变量
            foreach (var block in blocks)
            {
                if (block.StDefinition != null)
                {
                    // 使用ST定义中的函数名作为类型
                    var varType = block.StDefinition.FunctionName;
                    declarations.AppendLine($"    {block.InstanceName} : {varType};");
                }
                else
                {
                    // 使用块类型作为后备
                    declarations.AppendLine($"    {block.InstanceName} : {block.DwgInfo.Name};");
                }
            }

            // 生成IO变量
            declarations.AppendLine();
            declarations.AppendLine("    (* IO Variables *)");

            var allInputs = blocks.SelectMany(b => b.InputPorts).Select(p => p.Name).Distinct();
            foreach (var input in allInputs)
            {
                declarations.AppendLine($"    {input} : REAL;");
            }

            var allOutputs = blocks.SelectMany(b => b.OutputPorts).Select(p => p.Name).Distinct();
            foreach (var output in allOutputs)
            {
                declarations.AppendLine($"    {output} : REAL;");
            }

            // 生成临时变量
            if (_config.IncludeVariableDeclaration)
            {
                declarations.AppendLine();
                declarations.AppendLine("    (* Temporary Variables *)");
                declarations.AppendLine("    TempVar1 : REAL;");
                declarations.AppendLine("    TempVar2 : BOOL;");
            }

            var template = _templateEngine.GetTemplate("VAR_DECLARATION");
            return template.Instantiate(new Dictionary<string, string>
            {
                ["declarations"] = declarations.ToString()
            });
        }

        private string GenerateMainLogic(List<IntegratedBlock> executionOrder, List<Connection> connections)
        {
            var logicBuilder = new StringBuilder();

            // 为每个执行层添加注释
            logicBuilder.AppendLine("(* ===== Main Program Logic ===== *)");
            logicBuilder.AppendLine();

            // 生成每个块的代码
            for (int i = 0; i < executionOrder.Count; i++)
            {
                var block = executionOrder[i];
                var stepComment = $"Step {i + 1}: {block.InstanceName}";

                logicBuilder.AppendLine($"(* {stepComment} *)");

                if (block.StDefinition?.Code != null && block.StDefinition.Code.Count > 0)
                {
                    // 如果有ST定义代码，使用它
                    foreach (var codeLine in block.StDefinition.Code)
                    {
                        logicBuilder.AppendLine($"    {codeLine}");
                    }
                }
                else
                {
                    // 否则生成通用函数块调用
                    var callCode = GenerateFunctionBlockCall(block);
                    logicBuilder.AppendLine($"    {callCode}");
                }

                logicBuilder.AppendLine();

                // 生成连接代码
                var blockConnections = connections.Where(c => c.SourceBlockId == block.Id).ToList();
                foreach (var conn in blockConnections)
                {
                    var assignment = $"{conn.TargetPort} := {conn.SourcePort};";
                    logicBuilder.AppendLine($"    {assignment}");
                }

                if (blockConnections.Any())
                    logicBuilder.AppendLine();
            }

            // 添加默认控制逻辑（如果块数较少）
            if (executionOrder.Count < 3)
            {
                logicBuilder.AppendLine(GenerateDefaultControlLogic());
            }

            return logicBuilder.ToString();
        }

        private string GenerateFunctionBlockCall(IntegratedBlock block)
        {
            var parameters = new StringBuilder();

            // 构建输入参数
            var inputParams = block.InputPorts.Select((port, idx) =>
                $"    {port.Name} := {GetDefaultValue(port.DataType)}");

            // 构建输出参数
            var outputParams = block.OutputPorts.Select((port, idx) =>
                $"    {port.Name} => {port.Name}_OUT");

            parameters.AppendLine(string.Join(",\n", inputParams.Concat(outputParams)));

            var template = _templateEngine.GetTemplate("FUNCTION_BLOCK_CALL");
            return template.Instantiate(new Dictionary<string, string>
            {
                ["instance_name"] = block.InstanceName,
                ["parameters"] = parameters.ToString(),
                ["comment"] = $"Execute {block.DwgInfo.Name}"
            });
        }

        private string GetDefaultValue(string dataType)
        {
            if (dataType == null)
                return "0";

            switch (dataType.ToUpper())
            {
                case "BOOL":
                    return "FALSE";
                case "INT":
                case "DINT":
                    return "0";
                case "REAL":
                    return "0.0";
                case "TIME":
                    return "T#0S";
                default:
                    return "0";
            }
        }

        private string GenerateDefaultControlLogic()
        {
            var logic = new StringBuilder();

            // 添加一些基本的控制逻辑模板
            if (_templateEngine.TemplateExists("IF_STATEMENT"))
            {
                var ifTemplate = _templateEngine.GetTemplate("IF_STATEMENT");

                logic.AppendLine("(* Default Control Logic *)");
                logic.Append(ifTemplate.Instantiate(new Dictionary<string, string>
                {
                    ["condition"] = "EmergencyStop = FALSE",
                    ["then_block"] = "    RunProcess := TRUE;\n",
                    ["else_block"] = "ELSE\n    RunProcess := FALSE;\n"
                }));
                logic.AppendLine();
            }

            return logic.ToString();
        }

        private string AssembleProgram(string programName, string variableCode, string logicCode)
        {
            if (_templateEngine.TemplateExists("PROGRAM_STRUCTURE"))
            {
                var programTemplate = _templateEngine.GetTemplate("PROGRAM_STRUCTURE");

                return programTemplate.Instantiate(new Dictionary<string, string>
                {
                    ["program_name"] = programName,
                    ["var_declaration"] = variableCode,
                    ["main_logic"] = logicCode
                });
            }

            // 后备方案：简单拼接
            return $@"PROGRAM {programName}
{variableCode}

BEGIN
{logicCode}
END_PROGRAM";
        }

        /// <summary>
        /// 生成示例代码（用于测试）
        /// </summary>
        public string GenerateExampleCode()
        {
            // 创建一个简单的示例系统
            var exampleBlocks = new List<SourceBlock>
            {
                new SourceBlock("Valve", "ControlValve",
                    new List<string> { "InputSignal", "Setpoint" },
                    new List<string> { "ValvePosition", "Status" }),
                new SourceBlock("Pump", "CentrifugalPump",
                    new List<string> { "StartCommand", "SpeedSetpoint" },
                    new List<string> { "ActualSpeed", "Running" }),
                new SourceBlock("Sensor", "PressureSensor",
                    new List<string> { "RawValue" },
                    new List<string> { "Pressure", "Alarm" })
            };

            var exampleStBlocks = new List<STFunBlockInfo>
            {
                new STFunBlockInfo
                {
                    BlockName = "Valve",
                    FunctionName = "ControlValve_FB",
                    Inputs = new List<string> { "InputSignal", "Setpoint" },
                    Outputs = new List<string> { "Position", "Status" },
                    Code = new List<string>
                    {
                        "Position := InputSignal * Setpoint;",
                        "Status := Position > 0.5;"
                    }
                },
                new STFunBlockInfo
                {
                    BlockName = "Pump",
                    FunctionName = "Pump_FB",
                    Inputs = new List<string> { "StartCmd", "SpeedSet" },
                    Outputs = new List<string> { "Speed", "Running" },
                    Code = new List<string>
                    {
                        "IF StartCmd THEN",
                        "    Speed := SpeedSet;",
                        "    Running := TRUE;",
                        "ELSE",
                        "    Speed := 0.0;",
                        "    Running := FALSE;",
                        "END_IF;"
                    }
                }
            };

            var result = GenerateFromEngineeringData(
                exampleBlocks,
                exampleStBlocks,
                new Dictionary<ObjectId, LineStruct>(),
                new Dictionary<ObjectId, BlockStruct>());

            return result.GeneratedCode;
        }
    }
}
